### PR TITLE
v4l2loopback: Fixup bytesused field when writer sends a too large value

### LINKED ISSUE #190: ffmpeg fails with unexpected number of bytes on gstreamer 1.0 input
#### Environment

* `v4l2loopback` version: 0.12.0
* kernel version: 4.18.12
* Distribution: Arch Linux
* ffmpeg version 4.0.2
* gstreamer version 1.14.4

#### Problem:

Using gstreamer 1.0 to push video into a v4l2loopback device and consuming it with ffmpeg leads to unexpected number of bytes in buffers in ffmpeg with certain (common?) resolutions/settings.

#### Repro:

Assuming that /dev/video1 is a v4l2loopback device,
  1. gst-launch-1.0 videotestsrc ! video/x-raw,format=YV12,width=1920,height=1080 ! v4l2sink device=/dev/video1
  2. ffmpeg -i /dev/video1 -pix_fmt yuv420p -f sdl -

Note that _certain_ other settings such as when using UYVY color + 1920x1200 resolution works.

#### Observed:

ffmpeg says:
[video4linux2,v4l2 @ 0x5581164f6280] Dequeued v4l2 buffer contains 3112960 bytes, but 3110400 were expected. Flags: 0x00000001.
/dev/video22: Invalid data found when processing input

#### Expected Results:

The input should be shown.

### LINKED ISSUE #448: Wrong incoming frame length
hi,

I'm using ubuntu-20.04 with v4l2loopback-0.12.3.

I have two v4l2 loopback devices with the following characteristics:
```
ffprobe /dev/video0

Input #0, video4linux2,v4l2, from '/dev/video0':
Duration: N/A, start: 17479.219834, bitrate: 331776 kb/s
Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 331776 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
```
```
ffprobe /dev/video1

Input #0, video4linux2,v4l2, from '/dev/video1':
Duration: N/A, start: 17481.786751, bitrate: 117964 kb/s
Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 640x512, 117964 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
```
but I ran into a problem with the frame size in webrtc source code: https://webrtc.googlesource.com/src/+/refs/heads/main/modules/video_capture/video_capture_impl.cc#132

for I420 the frame size in bytes should be `1280×720+640×360×2 == 1382400` but was read 1384448...

IncomingFrame() called from here: https://webrtc.googlesource.com/src/+/refs/heads/main/modules/video_capture/linux/video_capture_linux.cc#411

`struct v4l2_buffer` filled here: https://webrtc.googlesource.com/src/+/refs/heads/main/modules/video_capture/linux/video_capture_linux.cc#398

but pay attention, webrtc works great for my second video stream! (/dev/video1: yuv420p, 640x512)
so I think the problem is not in the webrtc code.

any ideas?

best!

### PR DESCRIPTION
**Pull request by jwrdegoede**
Gstreamer's v4l2sink is known to submit buffers with bytesused set to the length of the buffer instead of the size of the actual image-data within the buffer which is typically smaller due to buffer sizes being rounded op to a page-size:

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/2532

Despite this being a long standing issue and their being 2 merge-reqs:

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/3713 https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4527

to try and fix this it looks like this is not going to get fixed in gst's v4l2sink anytime soon and even if once it is fixed many users will likely be using an older v4l2sink which still has this bug.

These buffers with a too large bytes used value are causing issues with various apps which reject these buffers when reading from the v4l2loopback device, such as e.g. ffmpeg and firefox.

Add a pix_format_has_valid_sizeimage flag which gets set from vidioc_s_fmt_out() if dev->pix_format.sizeimage is known to have just been set to a valid, fixed size (so this e.g. won't be set for MJPG).

And then fix this issue by making vidioc_qbuf() truncate V4L2_BUF_TYPE_VIDEO_OUTPUT buffer's bytes_used value to dev->pix_format.sizeimage when this flag is set.

Closes #190
Closes #448
Obsoletes #435

### CODE REVIEW

File: v4l2loopback.c [hunk 1]
```diff
@@ -1717,7 +1734,18 @@ static int vidioc_qbuf(struct file *file, void *fh, struct v4l2_buffer *buf)
 			b->buffer.timestamp = buf->timestamp;
 			b->buffer.flags |= V4L2_BUF_FLAG_TIMESTAMP_COPY;
 		}
-		b->buffer.bytesused = buf->bytesused;
+		if (dev->pix_format_has_valid_sizeimage) {
+			if (buf->bytesused >= dev->pix_format.sizeimage) {
+				b->buffer.bytesused = dev->pix_format.sizeimage;
+			} else {
+				dev_warn_ratelimited(&dev->vdev->dev, "warning queued output buffer bytesused too small %d < %d\n",
```
[the remark this answers is not in the document]
Comment (jwrdegoede) [reply v4l2loopback.c:1741]: Ah I see you have just merged this with the clang-format fixes squashed in, so I guess there is no need to change anything here now ?

[the remark this answers is not in the document]
Comment (jwrdegoede) [reply v4l2loopback.c:1741]: And I see you've just pushed an extra commit fixing this, let me resolve his conversation then.

**Comment by jwrdegoede** [comment]
p.s.

Thank you for merging this quickly and thank you for the `dprintkrw()` fix you added.

File: v4l2loopback.c [hunk 2]
```diff
@@ -1717,7 +1734,18 @@ static int vidioc_qbuf(struct file *file, void *fh, struct v4l2_buffer *buf)
 			b->buffer.timestamp = buf->timestamp;
 			b->buffer.flags |= V4L2_BUF_FLAG_TIMESTAMP_COPY;
 		}
-		b->buffer.bytesused = buf->bytesused;
+		if (dev->pix_format_has_valid_sizeimage) {
+			if (buf->bytesused >= dev->pix_format.sizeimage) {
+				b->buffer.bytesused = dev->pix_format.sizeimage;
```
Comment (ndufresne) [inline v4l2loopback.c:1739]: Side note, the pix_format sizeimage is meant to be the padded size, so that you can use a third party allocator like DMABuf Heap. It seems that the sizeimage here is the "ideal" image size without padding. Maybe it has nothing to do, but this could also be the reason of the initial issue.

Comment (jwrdegoede) [reply v4l2loopback.c:1739]: > Side note, the pix_format sizeimage is meant to be the padded size, so that you can use a third party allocator like DMABuf Heap. It seems that the sizeimage here is the "ideal" image size without padding. Maybe it has nothing to do, but this could also be the reason of the initial issue.

I don't know where this notion comes from but AFAIK this simply is *not* true (and never has been for the 14 years I've worked on v4l2). If you need a size with which is a multiple of the page-size then you need to do the rounding up to the next page-size yourself.

https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/pixfmt-v4l2.html describes the `sizeimage` field as:

```
Size in bytes of the buffer to hold a complete image, set by the driver. Usually this is bytesperline times height. When the image consists of variable length compressed data this is the number of bytes required by the codec to support the worst-case compression scenario.

The driver will set the value for uncompressed images.

Clients are allowed to set the sizeimage field for variable length compressed data flagged with V4L2_FMT_FLAG_COMPRESSED at [ioctl VIDIOC_ENUM_FMT](https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-enum-fmt.html#vidioc-enum-fmt), but the driver may ignore it and set the value itself, or it may modify the provided value based on alignment requirements or minimum/maximum size requirements. If the client wants to leave this to the driver, then it should set sizeimage to 0.
```

No where does this say that this is padded / round up to the next page-size. The rounding up to page-size is done for the length field of mmap-ed buffers since mmaping is done per page.

Comment (ndufresne) [reply v4l2loopback.c:1739]: It has been documented that way since bytesperline is what most driver will align. I believe I already said page alignment is uncommon strict requirement. I take note to improve the doc for driver implementer, but to make external allocation work (if that matter to you) software like chromium need that to be accurate. Its quite likely though that page alignment is always obtained by accident. As for what size is that actual data needed, every application dealing with raw video should know this, there is no need for the driver to tell us.
